# -*- coding: utf-8 -*-
"""Shipment status.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ZccSLBaACNax4aUwR6WfIxBFeW6hKlX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("shipping_data_0.csv")

df.head()

df.columns

df.isnull().sum()

df = df.dropna()

df['Shipment_Status'] = df['on_time']

df['Shipment_Status'].value_counts()

le = LabelEncoder()

df['Shipment_Status'] = le.fit_transform(df['Shipment_Status'])

# The original 'Shipping_Mode' column does not exist in the DataFrame.
# This line has been removed to prevent a KeyError.
# Please ensure 'Shipping_Mode' is available if it's required for further analysis.

# Assuming 'product' column is intended to be encoded as 'Product_Category'.
df['Product_Category'] = LabelEncoder().fit_transform(df['product'])

X = df[['product_quantity',
        'Product_Category']]

y = df['Shipment_Status']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = RandomForestClassifier()

model.fit(X_train, y_train)

predictions = model.predict(X_test)

accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)

print(classification_report(
    y_test,
    predictions
))

print(confusion_matrix(
    y_test,
    predictions
))

df['Shipment_Status'].value_counts().plot(
    kind='bar'
)

plt.title('Shipment Status Distribution')
plt.show()

result = pd.DataFrame({
    'Actual': y_test,
    'Predicted': predictions
})

result.head()

result.to_excel(
    "Shipment_Prediction_Result.xlsx",
    index=False
)

from google.colab import files

files.download(
    "Shipment_Prediction_Result.xlsx"
)

import joblib

joblib.dump(model, 'shipment_model.pkl')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pandas
# scikit-learn
# joblib

import streamlit as st
import pandas as pd
import joblib

# Load trained model
model = joblib.load("shipment_model.pkl")

st.set_page_config(
    page_title="Shipment Status Prediction",
    page_icon="📦",
    layout="centered"
)

st.title("📦 Shipment Status Prediction")
st.write("Predict whether a shipment will be On Time, Delayed, Returned, or Cancelled.")

st.subheader("Enter Shipment Details")

distance = st.number_input(
    "Distance",
    min_value=0.0,
    value=100.0
)

shipping_mode = st.selectbox(
    "Shipping Mode",
    ["Standard", "Express", "Same Day"]
)

product_category = st.selectbox(
    "Product Category",
    ["Electronics", "Clothing", "Furniture"]
)

# Encoding values
shipping_mode_map = {
    "Standard": 0,
    "Express": 1,
    "Same Day": 2
}

product_category_map = {
    "Electronics": 0,
    "Clothing": 1,
    "Furniture": 2
}

if st.button("Predict Shipment Status"):

    input_data = pd.DataFrame({
        "Distance": [distance],
        "Shipping_Mode": [shipping_mode_map[shipping_mode]],
        "Product_Category": [product_category_map[product_category]]
    })

    prediction = model.predict(input_data)

    status_map = {
        0: "On Time",
        1: "Delayed",
        2: "Returned",
        3: "Cancelled"
    }

    result = status_map.get(prediction[0], "Unknown")

    st.success(f"Predicted Shipment Status: {result}")

st.markdown("---")
st.write("Machine Learning Internship Project")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import joblib
# 
# # Load trained model
# model = joblib.load('shipment_model.pkl')
# 
# st.set_page_config(
#     page_title='Shipment Status Prediction',
#     page_icon='📦',
#     layout='centered'
# )
# 
# st.title('📦 Shipment Status Prediction')
# st.write('Predict whether a shipment will be On Time, Delayed, Returned, or Cancelled.')
# 
# st.subheader('Enter Shipment Details')
# 
# # Note: 'Distance' was identified as not being used by the model
# # during the model training phase. The previous context also mentions
# # that 'Shipping_Mode' was removed due to non-existence in the dataset
# # for initial model training, but it appears here again. For consistency,
# # I will include `Distance` and `Shipping_Mode` as inputs if the model
# # was retrained with them. However, based on the `X` variable state,
# # the model was trained only on `product_quantity` and `Product_Category`.
# # I will adjust the app to reflect the model's actual inputs.
# 
# product_quantity = st.number_input(
#     'Product Quantity',
#     min_value=0,
#     value=1
# )
# 
# product_category_options = ['Electronics', 'Clothing', 'Furniture', 'Books', 'Home Appliances', 'Food']
# product_category_map = {
#     'Electronics': 0,
#     'Clothing': 1,
#     'Furniture': 2,
#     'Books': 3,
#     'Home Appliances': 4,
#     'Food': 5 # Adding more categories if not specified in problem statement
# }
# 
# product_category_input = st.selectbox(
#     'Product Category',
#     options=product_category_options
# )
# 
# # Convert selected product category to its numerical representation
# product_category_encoded = product_category_map.get(product_category_input, -1) # -1 for unknown/new category
# 
# if st.button('Predict Shipment Status'):
#     if product_category_encoded == -1:
#         st.error("Please select a valid Product Category.")
#     else:
#         input_data = pd.DataFrame({
#             'product_quantity': [product_quantity],
#             'Product_Category': [product_category_encoded]
#         })
# 
#         prediction = model.predict(input_data)
# 
#         status_map = {
#             0: 'On Time',
#             1: 'Delayed',
#             2: 'Returned',
#             3: 'Cancelled' # Assuming these are the potential output classes
#         }
# 
#         result = status_map.get(prediction[0], 'Unknown')
# 
#         st.success(f'Predicted Shipment Status: {result}')
# 
# st.markdown('---')
# st.write('Machine Learning Internship Project')